# spring.application.name=studentmanager
# server.port=8080
# spring.datasource.url=jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=school;encrypt=true;trustServerCertificate=true;
# spring.datasource.username=nguyen
# spring.datasource.password=11223344

# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# spring.thymeleaf.cache=false

# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql=TRACE

spring.datasource.url=${JDBC_DATABASE_URL}

spring.jpa.hibernate.ddl-auto=update

